networks:
  module_4_lab:
    # external: true
    driver: bridge
    name: module_4_lab

services:
  python_exporter:
    build:
      context: ./python_exporter
      dockerfile: Dockerfile
    image: python-exporter-prometheus-app
    container_name: python_exporter
    networks:
      - module_4_lab
    ports:
      - "8000:8000"
    restart: "no"

  custom_exporter:
    build:
      context: ./custom_exporter
      dockerfile: Dockerfile
    image: custom-exporter-prometheus-app
    container_name: custom_exporter
    networks:
      - module_4_lab
    ports:
      - "8001:8001"
    restart: "no"

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    networks:
      - module_4_lab
    ports:
      - "9100:9100"
    restart: "no"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - module_4_lab
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: "no"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - module_4_lab
    depends_on:
      - prometheus
    restart: "no"
