global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: "python_exporter"
    static_configs:
      - targets: ["python_exporter:8000"]

  - job_name: 'custom_exporter'
    metrics_path: /custom-metrics
    static_configs:
    - targets: ['custom_exporter:8001']
